language: java
git:
  depth: 9999
matrix:
  include:
  - os: linux
    jdk: openjdk8
    sudo: required
    services:
      - docker
    before_deploy: 
      - git config --local user.name "Open Identity Platform Community" && git config --local user.email "open-identity-platform-openidm@googlegroups.com"
      - git checkout -f $TRAVIS_BRANCH
      - git tag -f $git_version && git tag -d $git_version
      - git tag -f $git_version
      - mvn -q -B -DreleaseVersion="$git_version" -DtagNameFormat="@{project.version}" -DignoreSnapshots=true  -DpushChanges=false -DscmCommentPrefix="[ci skip] $TRAVIS_REPO_SLUG " -DskipTests -Darguments=-DskipTests -Dresume=false clean release:prepare 
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git >/dev/null 2>&1
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git $git_version >/dev/null 2>&1
    deploy:
      provider: releases
      draft: false
      prerelease: false
      target_commitish: $(git rev-list -n 1 $git_version)
      tag_name: $git_version
      name: $git_version
      body: "compare: $(git rev-list -n 1 $git_version_last)...$(git rev-list -n 1 $git_version)"
      api_key:
        secure: HZTjEQBYEtlu/fH8cq96CgqoG18azvcbMQ+ZLnLajDWVoFnrdmFCGFFm76UnX6qRr28Z+Pyyq8p9wdDw7bfxXsKULwwCVGzwwvFaiW3+w6rHK+uGbtQDBOcLrwPfgLyHrMnkecuRi1FNdow15gLb3fl+UvEcWTUNHwNN1rWV26gLyhpKdYCHQ4rkNX2ELpaC/3rc6IS2bes4XVKXK1EPWrgp5MJSuBY3PGOMF2Dx9w/rWuzhccDKXZA6TLw339vcO08jDzSGKqcSoWa4FRsI+3eTDHNjOMCHkYII1BE3TvNSj7ECPs7Y6gPOfbS8pXahuot0WIBr8OIurppRIUPkA+mezfsJlxfczv2S9HdW/dzawEQVH4HTPsZkY4rutrRRvPGCZc/Ewr7aELXHjLrPr49952qo9tAC9KmZhX68nO0VQ+wVcGYUcdIl+LVi9FMl+3gJLRoejgB7X3fY02WMm/vt4YuV+VwIkvQepIhqM48JvGGtKXJ9FM3X88YkBi35003EdOFAzd4I5esZZP++de3DCAnDp6tJnL7zqNu1WHf85zAmN3KJvChIWH7vYBiRYBhCrbeoclPh1Dc6Q9YME/5AlDHwuqrKjfx3fD9BCKnYB0QQIfN1Rv36qUtln7VkRA+83+1IVHZ1ZlBENSOPnDek4OlTfXkJi0fQ+nKJtMw=
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: 
        - "openidm-zip/target/*.zip"
        - "openidm-zip/Dockerfile"
      on:
        repo: OpenIdentityPlatform/OpenIDM
        tags: false
        branch: 
          - master
          - travis
    after_deploy:
      - echo 'after_deploy'
      - echo 'build and push Docker'
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build ./openidm-zip -t $DOCKER_USERNAME/openidm -t $DOCKER_USERNAME/openidm:$git_version
      - docker push $DOCKER_USERNAME/openidm:$git_version
      - docker push $DOCKER_USERNAME/openidm
  - os: osx
    osx_image: xcode9.1
  allow_failures:
  - os: osx
branches:
  except:
    - /[0-9]+\.[0-9]+\.[0-9]+$/
notifications:
  email:
    recipients:
      - open-identity-platform-openidm@googlegroups.com
    on_success: always
    on_failure: change
before_install:
  - date -u
  - uname -a
  - git fetch -t
  - export git_version_last="$(git describe --abbrev=0 --tags --always)"
  - export git_version="$(echo $git_version_last | awk -F . '{ printf "%d.%d.%d", $1,$2,$3 + 1}')"
  - env | sort
  - git log `git describe --tags --abbrev=0 HEAD^ --always`..HEAD --oneline 
install:
  - mvn -q -B -DskipTests -Dmaven.javadoc.skip=true clean install -f OpenICF/OpenDJ/forgerock-parent
  - mvn -q -B -DskipTests -Dmaven.javadoc.skip=true clean install -f OpenICF/OpenDJ 
  - mvn -q -B -DskipTests -Dmaven.javadoc.skip=true clean install -f OpenICF
script:
  - mvn -B clean install