////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-groovy]
== Groovy Connector Toolkit

OpenICF provides a generic Groovy Connector Toolkit that enables you to run a Groovy script for any OpenICF operation, such as search, update, create, and others, on any external resource.

The Groovy Connector Toolkit is not a complete connector in the traditional sense. Rather, it is a framework within which you must write your own Groovy scripts to address the requirements of your implementation. Specific scripts are provided within these samples, which demonstrate how the Groovy Connector Toolkit can be used. These scripts cannot be used as is in your deployment, but are a good starting point on which to base your customization.

[#groovy-connector]
=== Groovy Connector Toolkit

The Groovy Connector Toolkit is bundled with OpenIDM 4.5, in the JAR `openidm/connectors/groovy-connector-1.4.2.1.jar`.

Sample implementations are provided in xref:../samples-guide/chap-groovy-samples.adoc#chap-groovy-samples["Samples That Use the Groovy Connector Toolkit to Create Scripted Connectors"] in the __Samples Guide__.


[#sec-implemented-interfaces-org-forgerock-openicf-connectors-groovy-ScriptedConnector-1_4_2_1]
=== OpenICF Interfaces Implemented by the Scripted Groovy Connector

The Scripted Groovy Connector implements the following OpenICF interfaces.
--

xref:appendix-interfaces.adoc#interface-AuthenticationApiOp[Authenticate]::
Provides simple authentication with two parameters, presumed to be a user name and password.

xref:appendix-interfaces.adoc#interface-CreateApiOp[Create]::
Creates an object and its `uid`.

xref:appendix-interfaces.adoc#interface-DeleteApiOp[Delete]::
Deletes an object, referenced by its `uid`.

xref:appendix-interfaces.adoc#interface-ResolveUsernameApiOp[Resolve Username]::
Resolves an object by its username and returns the `uid` of the object.

xref:appendix-interfaces.adoc#interface-SchemaApiOp[Schema]::
Describes the object types, operations, and options that the connector supports.

xref:appendix-interfaces.adoc#interface-ScriptOnConnectorApiOp[Script on Connector]::
Enables an application to run a script in the context of the connector. Any script that runs on the connector has the following characteristics:
+

* The script runs in the same execution environment as the connector and has access to all the classes to which the connector has access.

* The script has access to a `connector` variable that is equivalent to an initialized instance of the connector. At a minimum, the script can access the connector configuration.

* The script has access to any script-arguments passed in by the application.


xref:appendix-interfaces.adoc#interface-ScriptOnResourceApiOp[Script on Resource]::
Runs a script on the target resource that is managed by this connector.

xref:appendix-interfaces.adoc#interface-SearchApiOp[Search]::
Searches the target resource for all objects that match the specified object class and filter.

xref:appendix-interfaces.adoc#interface-SyncApiOp[Sync]::
Polls the target resource for synchronization events, that is, native changes to objects on the target resource.

xref:appendix-interfaces.adoc#interface-TestApiOp[Test]::
Tests the connector configuration. Testing a configuration checks all elements of the environment that are referred to by the configuration are available. For example, the connector might make a physical connection to a host that is specified in the configuration to verify that it exists and that the credentials that are specified in the configuration are valid.

+
This operation might need to connect to a resource, and, as such, might take some time. Do not invoke this operation too often, such as before every provisioning operation. The test operation is not intended to check that the connector is alive (that is, that its physical connection to the resource has not timed out).

+
You can invoke the test operation before a connector configuration has been validated.

xref:appendix-interfaces.adoc#interface-UpdateApiOp[Update]::
Updates (modifies or replaces) objects on a target resource.

--


[#sec-config-properties-org-forgerock-openicf-connectors-groovy-ScriptedConnector-1_4_2_1]
=== Scripted Groovy Connector Configuration

The Scripted Groovy Connector has the following configurable properties.

[#operation-script-files-properties-org-forgerock-openicf-connectors-groovy-ScriptedConnector-1_4_2_1]
==== Operation Script Files Properties


[cols="33%,17%,16%,17%,17%", stripes=even]
|===
|Property |Type |Default |Encrypted |Required

a| `authenticateScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-AuthenticationApiOp[Authenticate]

5+a| The name of the file used to perform the AUTHENTICATE operation.

a| `deleteScriptFileName`
a| `String`
a| `null`
a|
a|xref:appendix-interfaces.adoc#interface-DeleteApiOp[Delete]

5+a| The name of the file used to perform the DELETE operation.

a| `schemaScriptFileName`
a| `String`
a| `null`
a|
a|xref:appendix-interfaces.adoc#interface-SchemaApiOp[Schema]

5+a| The name of the file used to perform the SCHEMA operation.

a| `customizerScriptFileName`
a| `String`
a| `null`
a|
a| No

5+a| The script used to customize some function of the connector. Read the documentation for more details.

a| `resolveUsernameScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-ResolveUsernameApiOp[Resolve Username]

5+a| The name of the file used to perform the RESOLVE_USERNAME operation.

a| `testScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-TestApiOp[Test]

5+a| The name of the file used to perform the TEST operation.

a| `updateScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-UpdateApiOp[Update]

5+a| The name of the file used to perform the UPDATE operation.

a| `searchScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-SearchApiOp[Search]

5+a| The name of the file used to perform the SEARCH operation.

a| `scriptOnResourceScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-ScriptOnResourceApiOp[Script on Resource]

5+a| The name of the file used to perform the RUNSCRIPTONRESOURCE operation.

a| `createScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-CreateApiOp[Create]

5+a| The name of the file used to perform the CREATE operation.

a| `syncScriptFileName`
a| `String`
a| `null`
a|
a| xref:appendix-interfaces.adoc#interface-SyncApiOp[Sync]

5+a| The name of the file used to perform the SYNC operation

|===


[#groovy-engine-configuration-properties-org-forgerock-openicf-connectors-groovy-ScriptedConnector-1_4_2_1]
==== Groovy Engine configuration Properties


[cols="33%,17%,16%,17%,17%", stripes=even]
|===
|Property |Type |Default |Encrypted |Required

a| `warningLevel`
a| `int`
a| `1`
a|
a| No

5+a| Warning Level of the compiler

a| `minimumRecompilationInterval`
a| `int`
a| `100`
a|
a| No

5+a| Sets the minimum of time after a script can be recompiled.

a| `scriptRoots`
a| `String[]`
a| `null`
a|
a| Yes

5+a| The root folder to load the scripts from. If the value is null or empty the classpath value is used.

a| `debug`
a| `boolean`
a| `false`
a|
a| No

5+a| If true, debugging code should be activated

a| `targetDirectory`
a| `File`
a| `null`
a|
a| No

5+a| Directory into which to write classes.

a| `disabledGlobalASTTransformations`
a| `String[]`
a| `null`
a|
a| No

5+a| Sets a list of global AST transformations which should not be loaded even if they are defined in `META-INF/org.codehaus.groovy.transform.ASTTransformation` files. By default, none is disabled.

a| `classpath`
a| `String[]`
a| `[]`
a|
a| No

5+a| Classpath for use during compilation.

a| `scriptExtensions`
a| `String[]`
a| `['groovy']`
a|
a| No

5+a| Script extensions

a| `sourceEncoding`
a| `String`
a| `UTF-8`
a|
a| No

5+a| Encoding for source files

a| `scriptBaseClass`
a| `String`
a| `null`
a|
a| No

5+a| Base class name for scripts (must derive from Script)

a| `verbose`
a| `boolean`
a| `false`
a|
a| No

5+a| If true, the compiler should produce action information

a| `recompileGroovySource`
a| `boolean`
a| `false`
a|
a| No

5+a| If set to true recompilation is enabled

a| `tolerance`
a| `int`
a| `10`
a|
a| No

5+a| The error tolerance, which is the number of non-fatal errors (per unit) that should be tolerated before compilation is aborted


|===


[#configuration-properties-org-forgerock-openicf-connectors-groovy-ScriptedConnector-1_4_2_1]
==== Configuration Properties


[cols="33%,17%,16%,17%,17%", stripes=even]
|===
|Property |Type |Default |Encrypted |Required

a| `customConfiguration`
a| `String`
a| `null`
a|
a| No

5+a| Custom Configuration script for Groovy ConfigSlurper

a| `customSensitiveConfiguration`
a| `GuardedString`
a| `null`
a| Yes
a| No

5+a| Custom Sensitive Configuration script for Groovy ConfigSlurper

|===



