////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-database]
== Database Table Connector

The Database Table connector enables provisioning to a single table in a JDBC database.

[#database-connector-config]
=== Configuring the Database Table Connector

A sample connector configuration for the Database Table connector is provided in `samples/provisioners/provisioner.openicf-contractordb.json`. The corresponding data definition language file is provided in `samples/provisioners/provisioner.openicf-contractordb.sql`.

The following excerpt shows the settings for the connector configuration properties in the sample Database Table connector:

[source, json]
----
"configurationProperties" :
    {
       "quoting" : "",
       "host" : "localhost",
       "port" : "3306",
       "user" : "root",
       "password" : "",
       "database" : "contractordb",
       "table" : "people",
       "keyColumn" : "UNIQUE_ID",
       "passwordColumn" : "",
       "jdbcDriver" : "com.mysql.jdbc.Driver",
       "jdbcUrlTemplate" : "jdbc:mysql://%h:%p/%d",
       "enableEmptyString" : false,
       "rethrowAllSQLExceptions" : true,
       "nativeTimestamps" : true,
       "allNative" : false,
       "validConnectionQuery" : null,
       "changeLogColumn" : "CHANGE_TIMESTEMP",
       "datasource" : "",
       "jndiProperties" : null
    },
----
The mandatory configurable properties are as follows:
--

`database`::
The JDBC database that contains the table to which you are provisioning.

`table`::
The name of the table in the JDBC database that contains the user accounts.

`keyColumn`::
The column value that is used as the unique identifier for rows in the table.

--


[#sec-implemented-interfaces-org-identityconnectors-databasetable-DatabaseTableConnector-1_1_0_2]
=== OpenICF Interfaces Implemented by the Database Table Connector

The Database Table Connector implements the following OpenICF interfaces.
--

xref:appendix-interfaces.adoc#interface-AuthenticationApiOp[Authenticate]::
Provides simple authentication with two parameters, presumed to be a user name and password.

xref:appendix-interfaces.adoc#interface-CreateApiOp[Create]::
Creates an object and its `uid`.

xref:appendix-interfaces.adoc#interface-DeleteApiOp[Delete]::
Deletes an object, referenced by its `uid`.

xref:appendix-interfaces.adoc#interface-ResolveUsernameApiOp[Resolve Username]::
Resolves an object by its username and returns the `uid` of the object.

xref:appendix-interfaces.adoc#interface-SchemaApiOp[Schema]::
Describes the object types, operations, and options that the connector supports.

xref:appendix-interfaces.adoc#interface-ScriptOnConnectorApiOp[Script on Connector]::
Enables an application to run a script in the context of the connector. Any script that runs on the connector has the following characteristics:
+

* The script runs in the same execution environment as the connector and has access to all the classes to which the connector has access.

* The script has access to a `connector` variable that is equivalent to an initialized instance of the connector. At a minimum, the script can access the connector configuration.

* The script has access to any script-arguments passed in by the application.


xref:appendix-interfaces.adoc#interface-SearchApiOp[Search]::
Searches the target resource for all objects that match the specified object class and filter.

xref:appendix-interfaces.adoc#interface-SyncApiOp[Sync]::
Polls the target resource for synchronization events, that is, native changes to objects on the target resource.

xref:appendix-interfaces.adoc#interface-TestApiOp[Test]::
Tests the connector configuration. Testing a configuration checks all elements of the environment that are referred to by the configuration are available. For example, the connector might make a physical connection to a host that is specified in the configuration to verify that it exists and that the credentials that are specified in the configuration are valid.

+
This operation might need to connect to a resource, and, as such, might take some time. Do not invoke this operation too often, such as before every provisioning operation. The test operation is not intended to check that the connector is alive (that is, that its physical connection to the resource has not timed out).

+
You can invoke the test operation before a connector configuration has been validated.

xref:appendix-interfaces.adoc#interface-UpdateApiOp[Update]::
Updates (modifies or replaces) objects on a target resource.

--


[#sec-config-properties-org-identityconnectors-databasetable-DatabaseTableConnector-1_1_0_2]
=== Database Table Connector Configuration

The Database Table Connector has the following configurable properties.

[#configuration-properties-org-identityconnectors-databasetable-DatabaseTableConnector-1_1_0_2]
==== Configuration Properties


[cols="33%,17%,16%,17%,17%", stripes=even]
|===
|Property |Type |Default |Encrypted |Required

a| `quoting`
a| `String`
a|
a|
a| No
5+a| Select whether database column names for this resource should be quoted, and the quoting characters. By default, database column names are not quoted (None). For other selections (Single, Double, Back, or Brackets), column names will appear between single quotes, double quotes, back quotes, or brackets in the SQL generated to access the database.

a| `host`
a| `String`
a|
a|
a| No
5+a| Enter the name of the host on which the database is running.

a| `port`
a| `String`
a|
a|
a| No
5+a| Enter the port number on which the database server is listening..

a| `user`
a| `String`
a|
a|
a| No
5+a| Enter the name of the mandatory Database user with permission to access the accounts table.

a| `password`
a| `GuardedString`
a| `null`
a| Yes
a| No

5+a| Enter a user account that has permission to access the accounts table.

a| `database`
a| `String`
a|
a|
a| No

5+a| Enter the name of the database on the database server that contains the table.

a| `table`
a| `String`
a|
a|
a| Yes

5+a| Enter the name of the table in the database that contains the accounts.

a| `keyColumn`
a| `String`
a|
a|
a| Yes

5+a| This mandatory column value will be used as the unique identifier for rows in the table.

a| `passwordColumn`
a| `String`
a|
a|
a| No

5+a| Enter the name of the column in the table that will hold the password values. If empty, no validation is done on resources and passwords.

a| `jdbcDriver`
a| `String`
a| `oracle.jdbc.driver.OracleDriver`
a|
a| No

5+a| Specify the JDBC Driver class name. For Oracle: oracle.jdbc.driver.OracleDriver. For MySQL: org.gjt.mm.mysql.Driver. Can be empty if datasource is provided.

a| `jdbcUrlTemplate`
a| `String`
a| `jdbc:oracle:thin:@%h:%p:%d`
a|
a| No

5+a| Specify the JDBC Driver Connection URL. Oracle template is jdbc:oracle:thin:@[host]:[port(1521)]:[DB]. MySQL template is jdbc:mysql://[host]:[port(3306)]/[db], for more info, read the JDBC driver documentation. Could be empty if datasource is provided

a| `enableEmptyString`
a| `boolean`
a| `false`
a|
a| No

5+a| Select to enable support for writing an empty string, instead of a NULL value, in character based columns defined as not-null in the table schema. This option does not influence the way strings are written for Oracle based tables. By default empty strings are written as a NULL value.

a| `rethrowAllSQLExceptions`
a| `boolean`
a| `true`
a|
a| No

5+a| If this is not checked, SQL statements which throw SQLExceptions with a 0 ErrorCode will be have the exception caught and suppressed. Check it to have exceptions with 0 ErrorCodes rethrown.

a| `nativeTimestamps`
a| `boolean`
a| `false`
a|
a| No

5+a| Select to retrieve Timestamp data type of the columns in java.sql.Timestamp format from the database table.

a| `allNative`
a| `boolean`
a| `false`
a|
a| No

5+a| Select to retrieve all data types of columns in native format from the database table.

a| `validConnectionQuery`
a| `String`
a| `null`
a|
a| No

5+a| Specify whether the check connection alive query should be used. If empty, the default implementation checks the connection by switching autocommit on/off. It might be more efficient to test the connection by selecting 1 from a dummy table.

a| `changeLogColumn`
a| `String`
a| `{empty}`
a|
a| xref:appendix-interfaces.adoc#interface-SyncApiOp[Sync]

5+a| The change log column stores the latest change time. Providing this value the Sync capabilities are activated.

a| `datasource`
a| `String`
a| `{empty}`
a|
a| No

5+a| If specified, the connector will attempt to connect using only this data source, and will ignore other specified resource parameters. For example: jdbc/SampleDataSourceName

a| `jndiProperties`
a| `String[]`
a| `null`
a|
a| No

5+a| Could be empty or enter the JDBC JNDI Initial context factory, context provider in a format: key = value.

a| `suppressPassword`
a| `boolean`
a| `true`
a|
a| No

5+a| If set to true then the password will not be returned. Never. Even though it is explicitly requested. If set to false then the password will be returned if it is explicitly requested.

|===


