////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.
 
  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.
 
  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions copyright [year] [name of copyright owner]".
 
  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////

:figure-caption!:
:example-caption!:
:table-caption!:


[#chap-csv]
== CSV File Connector

The CSV file connector is useful when importing users, either for initial provisioning or for ongoing updates. When used continuously in production, a CSV file serves as a change log, often containing only user records that have changed.

[#csv-connector-config]
=== Configuring the CSV File Connector

A sample CSV file connector configuration is provided in `openidm/samples/provisioners/provisioner.openicf-csv.json`.

The following example shows an excerpt of the provisioner configuration. The `connectorHostRef` property is optional and must be provided only if the connector runs remotely.

[source, json]
----
{
  "connectorRef": {
    "connectorHostRef": "#LOCAL",
    "bundleName"    : "org.openidentityplatform.openicf.connectors.csvfile-connector",
    "bundleVersion" : "[2.0.0.0,3)",
    "connectorName" : "org.forgerock.openicf.csvfile.CSVFileConnector"
  }
}
----
The following excerpt shows the __required__ configuration properties:

[source, javascript]
----
"configurationProperties" : {
    "csvFile" : "&{launcher.project.location}/data/hr.csv",
    "headerUid" : "uid"
},
----
--

`csvFile`::
The path to the CSV file that is the data source for this connector.

`headerUid`::
The CSV header that maps to the `uid` (or name) for each row.

+
Default: `uid`

--
--
The CSV file connector also supports following optional configuration properties:

`encoding`::
Default: `utf-8`

`headerPassword`::
The CSV header that maps to the password for each row. Use this property when password-based authentication is required.

`fieldDelimiter`::
The character in the CSV file that is used to separate field values.

+
Default: `,`

`quoteCharacter`::
The character in the CSV file that is used to encapsulate strings.

+
Default: `"`

`newlineString`::
The character string in the CSV file that is used to terminate each line.

+
Default: `\n`

`syncFileRetentionCount`::
The number of historical copies of the CSV file to retain when performing synchronization operations.

+
Default: `3`

--


[#sec-implemented-interfaces-org-forgerock-openicf-csvfile-CSVFileConnector-1_5_1_4]
=== OpenICF Interfaces Implemented by the CSV File Connector

The CSV File Connector implements the following OpenICF interfaces.
--

xref:appendix-interfaces.adoc#interface-AuthenticationApiOp[Authenticate]::
Provides simple authentication with two parameters, presumed to be a user name and password.

xref:appendix-interfaces.adoc#interface-BatchApiOp[Batch]::
Execute a series of operations in a single request.

xref:appendix-interfaces.adoc#interface-CreateApiOp[Create]::
Creates an object and its `uid`.

xref:appendix-interfaces.adoc#interface-DeleteApiOp[Delete]::
Deletes an object, referenced by its `uid`.

xref:appendix-interfaces.adoc#interface-ResolveUsernameApiOp[Resolve Username]::
Resolves an object by its username and returns the `uid` of the object.

xref:appendix-interfaces.adoc#interface-SchemaApiOp[Schema]::
Describes the object types, operations, and options that the connector supports.

xref:appendix-interfaces.adoc#interface-ScriptOnConnectorApiOp[Script on Connector]::
Enables an application to run a script in the context of the connector. Any script that runs on the connector has the following characteristics:
+

* The script runs in the same execution environment as the connector and has access to all the classes to which the connector has access.

* The script has access to a `connector` variable that is equivalent to an initialized instance of the connector. At a minimum, the script can access the connector configuration.

* The script has access to any script-arguments passed in by the application.


xref:appendix-interfaces.adoc#interface-SearchApiOp[Search]::
Searches the target resource for all objects that match the specified object class and filter.

xref:appendix-interfaces.adoc#interface-SyncApiOp[Sync]::
Polls the target resource for synchronization events, that is, native changes to objects on the target resource.

xref:appendix-interfaces.adoc#interface-TestApiOp[Test]::
Tests the connector configuration. Testing a configuration checks all elements of the environment that are referred to by the configuration are available. For example, the connector might make a physical connection to a host that is specified in the configuration to verify that it exists and that the credentials that are specified in the configuration are valid.

+
This operation might need to connect to a resource, and, as such, might take some time. Do not invoke this operation too often, such as before every provisioning operation. The test operation is not intended to check that the connector is alive (that is, that its physical connection to the resource has not timed out).

+
You can invoke the test operation before a connector configuration has been validated.

xref:appendix-interfaces.adoc#interface-UpdateApiOp[Update]::
Updates (modifies or replaces) objects on a target resource.

--


[#sec-config-properties-org-forgerock-openicf-csvfile-CSVFileConnector-1_5_1_4]
=== CSV File Connector Configuration

The CSV File Connector has the following configurable properties.

[#configuration-properties-org-forgerock-openicf-csvfile-CSVFileConnector-1_5_1_4]
==== Configuration Properties


[cols="33%,17%,16%,17%,17%"]
|===
|Property |Type |Default |Encrypted |Required 
|===



