ALTER TABLE SOPENIDM.GENERICOBJECTPROPERTIES ADD PRIMARY KEY (GENERICOBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.MANAGEDOBJECTPROPERTIES ADD PRIMARY KEY (MANAGEDOBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.CONFIGOBJECTPROPERTIES ADD PRIMARY KEY (CONFIGOBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.SCHEDULEROBJECTPROPERTIES ADD PRIMARY KEY (SCHEDULEROBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.CLUSTEROBJECTPROPERTIES ADD PRIMARY KEY (CLUSTEROBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.UPDATEOBJECTPROPERTIES ADD PRIMARY KEY (UPDATEOBJECTS_ID, PROPKEY);
ALTER TABLE SOPENIDM.RELATIONSHIPPROPERTIES ADD PRIMARY KEY (RELATIONSHIPS_ID, PROPKEY);
