apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: getting-started
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi