
metadata:
  name: postgres
  labels:
    app: getting-started
spec:
  selector:
    matchLabels:
      app: getting-started
      tier: repo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: getting-started
        tier: repo
    spec:
      containers:
      - image: forgerock/openidm-postgres:latest
        name: postgres
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: openidm
        - name: POSTGRES_USER
          value: openidm
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        #- name: MYSQL_ROOT_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysql-pass
        #      key: password.txt
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pv-claim
